#!/bin/sh

# redis setup
mkdir -p /var/log/redis
chown -R redis:redis /var/log/redis
chmod -R 0755 /var/log/redis

# enable redis
echo 'redis_enable="YES"' > /etc/rc.conf.d/redis

# load redis-ml module
sed -i '' 's/# loadmodule \/path\/to\/other_module.so/loadmodule \/usr\/local\/lib\/redis-ml.so/' /usr/local/etc/redis.conf